id: P377E3E03
initial_creation_type: ocr
source_metadata:
  volumes:
    3ec58dd0f9e44320ab4cf4f9d521c5e9:
      base_file: v075.txt
      image_group_id: I1PD95920
      title: རྣམ་བཤད་བསྡུ་བ།
      total_pages: 1529
      volume_number: 75
