id: P377E3E03
initial_creation_type: ocr
source_metadata:
  volumes:
    b628ad7b699f4725804ac5632889eac1:
      base_file: v075.txt
      image_group_id: I1PD95920
      title: རྣམ་བཤད་བསྡུ་བ།
      total_pages: 1529
      volume_number: 75
